# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal git-2

DESCRIPTION="protocol agnostic two phase commit implementation"
HOMEPAGE="http://hackage.haskell.org/package/2pc"
SRC_URI=""
EGIT_REPO_URI="git://github.com/qnikst/2pc-haskell.git"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/binary-0.6*:=[profile?]
		dev-haskell/mwc-random:=[profile?]
		=dev-haskell/stm-2.4*:=[profile?]
		dev-haskell/vector:=[profile?]
		>=dev-lang/ghc-7.6.1:="
DEPEND="${RDEPEND}
		test? ( =dev-haskell/hunit-1.2*
			>=dev-haskell/quickcheck-2.4
			<dev-haskell/quickcheck-2.6
			>=dev-haskell/test-framework-0.4
			<dev-haskell/test-framework-0.9
			>=dev-haskell/test-framework-hunit-0.2
			<dev-haskell/test-framework-hunit-0.4
			>=dev-haskell/test-framework-quickcheck2-0.2
			<dev-haskell/test-framework-quickcheck2-0.4
		)
		>=dev-haskell/cabal-1.8"
