# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.1

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal git-2

DESCRIPTION="Bindings to ZeroMQ 3.x (qnikst overlay)"
HOMEPAGE="http://github.com/twittner/zeromq-haskell/"
SRC_URI=""
EGIT_REPO_URI="git://github.com/qnikst/zeromq-haskell.git"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RDEPEND=">=dev-lang/ghc-6.10.4:=
		>=net-libs/zeromq-3"
DEPEND="${RDEPEND}
		test? ( >=dev-haskell/quickcheck-2.4
			>=dev-haskell/test-framework-0.4
			>=dev-haskell/test-framework-quickcheck2-0.2
		)
		>=dev-haskell/cabal-1.8"
