# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal git-2

DESCRIPTION="eventfd support"
HOMEPAGE="http://hackage.haskell.org/package/eventfd"
SRC_URI=""
EGIT_REPO_URI="git://github.com/qnikst/eventfd.git"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-7.4.1:="
DEPEND="${RDEPEND}
		test? ( dev-haskell/async
			dev-haskell/hspec
			dev-haskell/hunit
		)
		>=dev-haskell/cabal-1.8"
