# Copyright 1999-2012 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal git-2

DESCRIPTION="FFI bindings to libvirt virtualization API (http://libvirt.org)"
HOMEPAGE="http://redmine.iportnov.ru/projects/libvirt-hs"
SRC_URI=""
EGIT_REPO_URI="git://github.com/qnikst/libvirt-hs.git"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS=""
IUSE=""

RDEPEND=">=dev-haskell/syb-0.1.0.2:=[profile?]
		>=dev-lang/ghc-6.10.4:=
		app-emulation/libvirt"
DEPEND="${RDEPEND}
		dev-haskell/c2hs
		>=dev-haskell/cabal-1.6"
